[workspace]
resolver = "2"
members = [
    "backend", 
    "cluster", 
    "cmd",
]

[workspace.dependencies]
anyhow = "1.0"
bytes = "1.6"
dashmap = "6.0"
figment = { version = "0.10", features = ["yaml"] }
log = { version = "0.4", features = ["kv", "kv_serde", "serde"] }
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
rocket = { version = "0.5", features = ["json", "tls", "uuid"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = { version = "0.12", features = ["paris"] }
sled = "0.34"
thiserror = "1.0"
tokio = { version = "1.39", features = ["full"] }
utoipa = { version = "4.2", features = ["rocket_extras"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["rocket"] }
